# jobs 用于执行不同的build stage
jobs:
  include:
    - stage: test
    - stage: deployAPK
    - stage: deployIPA

    - stage: test
      os: linux
      language: generic
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # Flutter依赖
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
      script:
        - "./flutter/bin/flutter upgrade"
        - "./flutter/bin/flutter test"
    - stage: deployAPK
      os: linux
      language: android
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      # 以上都是在安装AndroidSDK
      env: APK_OUTPUT=build/app/outputs/apk/release/app-release.apk
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      #以上为Flutter环境搭建
      before_script:
        # 用你自己的解密命令替代
        - openssl aes-256-cbc -K $encrypted_275e96c4265b_key -iv $encrypted_275e96c4265b_iv -in key.properties.enc -out key.properties -d
        - openssl aes-256-cbc -K $encrypted_275e96c4265b_key -iv $encrypted_275e96c4265b_iv -in flutter_test.jks.enc -out flutter_test.jks -d
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
      script:
        - "./flutter/bin/flutter upgrade"
        - "./flutter/bin/flutter -v build apk --release"
      deploy:
        provider: releases
        skip_cleanup: true
        # 用你的api_key替代
        api_key:
          secure: uDRE0d3gZ5JYhl/jBiDp5z...
        file: $APK_OUTPUT
        on:
          tags: true

    - stage: deployIPA
      os: osx
      language: objective-c
      osx_image: xcode9.2
      before_script:
        - pip2 install six
        - brew update
        - brew install libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        # 以上安装xcode环境
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
      script:
        - "./flutter/bin/flutter upgrade"
        - gem install cocoapods
        - pod setup
        - "./flutter/bin/flutter -v build ios --release --no-codesign"
        - mkdir Runner
        - mkdir Runner/Payload
        - cp -r build/ios/iphoneos/Runner.app Runner/Payload/Runner.app
        - cd Runner
        - zip -r Runner.ipa Payload
      deploy:
        provider: releases
        skip_cleanup: true
        #跟Android的api_key是一致的
        api_key:
          secure: uDRE0d3gZ5JYhl/jBiDp5zv32fH...
        file: Runner.ipa
        on:
          tags: true
